version: '3.7'

services:
  db:
    image: postgres
    container_name: db_games
    volumes:
      - db_games_vol:/var/lib/postgresql/data
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
  web:
    build: .
    container_name: games
    command: >
      sh -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/games
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.dev
volumes:
  db_games_vol:
