repos:
- repo: https://github.com/pre-commit/mirrors-isort
  rev: "v5.9.3"
  hooks:
  - id: isort
    args: [--profile=black]
    
- repo: https://github.com/pycqa/flake8.git
  rev: 6.0.0
  hooks:
  - id: flake8
    args: [
      "--ignore=E501"
    ]
    additional_dependencies: [
      "flake8-bugbear",
      "flake8-builtins",
      "pep8-naming",
      "flake8-commas",
      "flake8-quotes",
      "flake8-todo",
      "flake8-django",
      "flake8-cognitive-complexity",
      "flake8-isort",
   ]
