services:
  payments:
    volumes:
      - type: bind
        source: ./
        target: /home/app/web
    ports:
      - "8000:8000"

  payments_db:
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    ports:
    - "6379:6379"

  worker:
    volumes:
      - ./:/home/app/web
  
  beat:
    volumes:
      - ./:/home/app/web

  nginx:
    image: nginx:1.23.4-alpine
    volumes:
      - ./static/:/static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 80
    depends_on:
      - payments

  node:
    image: node:19-alpine
    volumes:
      - ./scripts/node.sh:/node.sh
    command: >
      sh -c "npm install -g localtunnel && sh node.sh"